sudo: required
languaje: node_js
node_js:
    - "9"
services:
    - docker
    - mongodb
env:
    -MONGO_URL='mongodb://localhost/carnets'
before_install:
    - wget -q0- https://toolbelt.heroku.com/install.sh | sh
install:
    - npm install
    - npm install -g npm@latest
    - npm i core-util-is
script:
    - npm test
    - docker build -t aseguradora-conductores . 
deploy:
    provider: script
    skip_cleanup: true
    script:
        heroku container:login;
        heroku container:push web -a $HEROKU_APP_NAME;
        heroku container:release web -a $HEROKU_APP_NAME;
    branch: master